on:
  pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Usa Action checkout
        uses: actions/checkout

      - name: Setup do node
        uses: actions/setup-node
        with:
          node-version: '12'

      - name: Intala dependencias
        run: npm install

      - name: Executa eslint
        run: npx eslint .